name: Docker Build via  Terraform

on:
  push:
    branches:
      - master

env:
  REGISTRY_URL: docker.io
  IMAGE_NAME: my-gh-ubuntu

permissions:
  contents: read

jobs:
  terraform-build-and-push:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: container-pipeline-1
    steps:
      - name: Output runner name
        outputs:
          RUNNER: ${{ runner.name}}
        run: echo "RUNNER_NAME=${{ runner.name }}" 

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (for cross-arch builds, optional)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PAT }}


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1


      - name: Terraform Init
        run: terraform init -input=false -backend=false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
